# extending from nginx officia image

FROM nginx:latest

# setting project working directory

WORKDIR /usr/share/nginx/html

# copying files from local host to image container

COPY index.html index.html

# NO EXPOSE  and CMD commands since they have been declared in the FROM official image